CREATE TABLE [dbo].[mlb_gameday_at_bats](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[game_id] [nvarchar](255) NULL DEFAULT (NULL),
	[inning] [int] NULL DEFAULT (NULL),
	[num] [int] NULL DEFAULT (NULL),
	[ball] [int] NULL DEFAULT (NULL),
	[strike] [int] NULL DEFAULT (NULL),
	[outs] [int] NULL DEFAULT (NULL),
	[batter_id] [int] NULL DEFAULT (NULL),
	[pitcher_id] [int] NULL DEFAULT (NULL),
	[stand] [nvarchar](255) NULL DEFAULT (NULL),
	[des] [text] NULL,
	[event] [nvarchar](255) NULL DEFAULT (NULL),
	[p_throws] [nvarchar](1) NULL DEFAULT (NULL),
	[on_first] [int] NULL DEFAULT (NULL),
	[on_second] [int] NULL DEFAULT (NULL),
	[on_third] [int] NULL DEFAULT (NULL),
	[pitcher_role] [nvarchar](1) NULL DEFAULT (NULL),
	[HOME_AWAY_BINARY] [int] NULL DEFAULT (NULL),
	[hfa] [tinyint] NULL DEFAULT (NULL),
	[BATTED_BALL_TYPE] [char](1) NULL DEFAULT (NULL),
	[catcher_id] [int] NULL DEFAULT (NULL),
	[is_top] [tinyint] NULL DEFAULT (NULL),
	[pit_retro_manager_id] [nvarchar](255) NULL DEFAULT (NULL),
	[bat_retro_manager_id] [nvarchar](255) NULL DEFAULT (NULL),
	[first_id] [int] NULL DEFAULT (NULL),
	[second_id] [int] NULL DEFAULT (NULL),
	[third_id] [int] NULL DEFAULT (NULL),
	[ss_id] [int] NULL DEFAULT (NULL),
	[lf_id] [int] NULL DEFAULT (NULL),
	[rf_id] [int] NULL DEFAULT (NULL),
	[cf_id] [int] NULL DEFAULT (NULL),
	[fielder_pos] [nvarchar](5) NULL DEFAULT (NULL),
	[fielder_id] [int] NULL DEFAULT (NULL),
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
